"""Telnyx AI Assistant setup utilities for EVA benchmarking."""

import json
from pathlib import Path
from typing import Any

import aiohttp

from eva.models.agents import AgentConfig, AgentTool
from eva.utils.logging import get_logger

logger = get_logger(__name__)


class TelnyxAssistantManager:
    """Create and manage Telnyx AI assistants for benchmark runs."""

    def __init__(
        self,
        api_key: str,
        api_base: str = "https://api.telnyx.com",
        session: aiohttp.ClientSession | None = None,
    ):
        self.api_key = api_key
        self.api_base = api_base.rstrip("/")
        self._session_owner = session is None
        self.session = session or aiohttp.ClientSession(
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            timeout=aiohttp.ClientTimeout(total=30.0),
        )

    async def create_benchmark_assistant(
        self,
        agent_config: AgentConfig,
        agent_config_path: str,
        webhook_base_url: str,
        model: str = "telnyx-llm-gpt-4o",
        voice: str | None = None,
    ) -> str:
        """Create a Telnyx assistant configured to call EVA tool webhooks."""
        assistant_payload = self._build_assistant_payload(
            agent_config=agent_config,
            agent_config_path=agent_config_path,
            webhook_base_url=webhook_base_url,
            model=model,
            voice=voice,
        )

        url = f"{self.api_base}/v2/ai/assistants"
        logger.info(f"Creating Telnyx benchmark assistant for agent {agent_config.id}")

        async with self.session.post(url, json=assistant_payload) as response:
            payload = await self._parse_response_json(response)
            if response.status >= 400:
                raise RuntimeError(
                    f"Failed to create Telnyx assistant: {response.status} {json.dumps(payload, sort_keys=True)}",
                )

        assistant_id = str(payload.get("id", "")).strip()
        if not assistant_id:
            raise RuntimeError(f"Telnyx assistant creation response did not include an id: {payload}")

        logger.info(f"Created Telnyx benchmark assistant {assistant_id} for agent {agent_config.id}")
        return assistant_id

    async def delete_assistant(self, assistant_id: str) -> None:
        """Delete a Telnyx benchmark assistant."""
        url = f"{self.api_base}/v2/ai/assistants/{assistant_id}"
        logger.info(f"Deleting Telnyx benchmark assistant {assistant_id}")

        async with self.session.delete(url) as response:
            payload = await self._parse_response_json(response)
            if response.status >= 400:
                raise RuntimeError(
                    f"Failed to delete Telnyx assistant {assistant_id}: "
                    f"{response.status} {json.dumps(payload, sort_keys=True)}",
                )

        logger.info(f"Deleted Telnyx benchmark assistant {assistant_id}")

    async def close(self) -> None:
        """Close the underlying HTTP session if owned by the manager."""
        if self._session_owner and not self.session.closed:
            await self.session.close()

    @staticmethod
    async def _parse_response_json(response: aiohttp.ClientResponse) -> dict[str, Any]:
        try:
            payload = await response.json()
        except aiohttp.ContentTypeError:
            payload = {"message": await response.text()}
        return payload if isinstance(payload, dict) else {"data": payload}

    def _build_assistant_payload(
        self,
        agent_config: AgentConfig,
        agent_config_path: str,
        webhook_base_url: str,
        model: str,
        voice: str | None,
    ) -> dict[str, Any]:
        normalized_webhook_base = webhook_base_url.rstrip("/")

        payload: dict[str, Any] = {
            "name": f"EVA Benchmark - {agent_config.name}",
            "description": (
                f"Auto-generated by EVA from {Path(agent_config_path).name} "
                f"for benchmark agent {agent_config.id}."
            ),
            "instructions": self._build_system_prompt(agent_config),
            "model": model,
            "tools": [self._build_webhook_tool(tool, normalized_webhook_base) for tool in agent_config.tools],
            "enabled_features": ["telephony"],
            "telephony_settings": {
                "supports_unauthenticated_web_calls": True,
            },
            "widget_settings": {
                "default_state": "expanded",
            },
        }
        if voice:
            payload["voice_settings"] = {"voice": voice}
        return payload

    @staticmethod
    def _build_system_prompt(agent_config: AgentConfig) -> str:
        sections = [
            agent_config.description.strip(),
            f"Role: {agent_config.role.strip()}",
            agent_config.personality.strip() if agent_config.personality else "",
            agent_config.instructions.strip(),
        ]
        return "\n\n".join(section for section in sections if section)

    @staticmethod
    def _build_webhook_tool(tool: AgentTool, webhook_base_url: str) -> dict[str, Any]:
        return {
            "type": "webhook",
            "webhook": {
                "name": tool.id,
                "description": tool.description,
                "url": f"{webhook_base_url}/tools/{{{{call_control_id}}}}/{tool.id}",
                "method": "POST",
                "body_parameters": {
                    "type": "object",
                    "properties": tool.get_parameter_properties(),
                    "required": tool.get_required_param_names(),
                },
            },
        }
